language: cpp
sudo: true
dist: trusty

env:
    - DOXYFILE=doc/api/DoxyfileHTML PATH=$HOME/.local/usr/bin:$PATH

before_script:
    - ./scripts/travis-before-script.sh

install:
    - ./scripts/travis-install.sh

script:
    - ./scripts/travis-script.sh

after_success:
    - ./scripts/travis-after-success.sh
